if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    set(VCPKG_TARGET_TRIPLET "${VCPKG_ARCH}-linux-release")
elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    set(VCPKG_TARGET_TRIPLET "${VCPKG_ARCH}-windows-static-md-release")
elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
    set(VCPKG_TARGET_TRIPLET "${VCPKG_ARCH}-osx-release")
else()
    message(FATAL_ERROR "Unsupported system: ${CMAKE_HOST_SYSTEM_NAME}")
endif()
set(CMAKE_TOOLCHAIN_FILE ${CMAKE_CURRENT_SOURCE_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake CACHE STRING "Vcpkg toolchain file")