name: Release
on:
  push:
    tags:
      - '**'

concurrency:
  group: ci-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/reusable_build.yml
    secrets: inherit

  release:
    permissions:
      contents: write
    needs: [build]
    runs-on: 'ubuntu-latest'
    steps:
      - name: Download amd64 plugin
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: libcontainer-amd64
          path: container-${{ github.ref_name }}-linux-x86_64

      - name: Download arm64 plugin
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: libcontainer-arm64
          path: container-${{ github.ref_name }}-linux-aarch64

      - name: Download osx plugin
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: libcontainer-osx
          path: container-${{ github.ref_name }}-osx-aarch64

      - name: Download win plugin
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: libcontainer-win
          path: container-${{ github.ref_name }}-win-x86_64

      - name: Create tarballs for release
        run: |
          tar -czvf container-${{ github.ref_name }}-linux-x86_64.tar.gz container-${{ github.ref_name }}-linux-x86_64/
          tar -czvf container-${{ github.ref_name }}-linux-aarch64.tar.gz container-${{ github.ref_name }}-linux-aarch64/
          tar -czvf container-${{ github.ref_name }}-osx-aarch64.tar.gz container-${{ github.ref_name }}-osx-aarch64/
          tar -czvf container-${{ github.ref_name }}-win-x86_64.tar.gz container-${{ github.ref_name }}-win-x86_64/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            container-${{ github.ref_name }}-linux-x86_64.tar.gz
            container-${{ github.ref_name }}-linux-aarch64.tar.gz
            container-${{ github.ref_name }}-osx-aarch64.tar.gz
            container-${{ github.ref_name }}-win-x86_64.tar.gz