name: Release
on:
  push:
    tags:
      - '**'

concurrency:
  group: ci-release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/reusable_build.yml
    secrets: inherit

  release:
    needs: [build]
    runs-on: 'ubuntu-latest'
    steps:
      - name: Download amd64 plugin
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: libcontainer-amd64

      - name: Rename amd64 library
        run: mv libcontainer.so libcontainer_amd64.so

      - name: Download arm64 plugin
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: libcontainer-arm64

      - name: Rename arm64 library
        run: mv libcontainer.so libcontainer_arm64.so

      - name: Download osx plugin
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: libcontainer-osx

      - name: Rename osx library
        run: mv libcontainer.dylib libcontainer_no_async_cap.dylib

      - name: Download win plugin
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: libcontainer-win

      - name: Rename win library
        run: mv container.dll container_no_async_cap.dll

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            libcontainer_amd64.so
            libcontainer_arm64.so
            libcontainer_no_async_cap.dylib
            container_no_async_cap.dll