name: Build plugin on all supported platforms

on:
  workflow_call:
    inputs:
      caching_enabled:
        description: 'whether to enable vcpkg caching'
        type: boolean
        required: false
        default: false

jobs:
  build-others:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      # Needed by vcpkg caching
      - name: Export GitHub Actions cache environment variables
        if: inputs.caching_enabled
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Export env variables for vcpkg caching
        if: inputs.caching_enabled
        run: echo "VCPKG_BINARY_SOURCES=clear;x-gha,readwrite" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go-worker/go.mod
          cache-dependency-path: go-worker/go.sum

      - name: Build plugin library
        run: make

      - name: Upload artifact - windows
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: libcontainer-win
          path: 'container.dll'

      - name: Upload artifact - osx
        if: ${{ matrix.os == 'macos-latest' }}
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: libcontainer-osx
          path: 'libcontainer.dylib'

  build-linux:
    name: build-linux-${{ matrix.arch }}
    runs-on: ${{ (matrix.arch == 'arm64' && 'ubuntu-24.04-arm') || 'ubuntu-24.04' }}
    strategy:
      fail-fast: false
      matrix:
        arch: [ amd64, arm64 ]
    steps:
      # Needed by vcpkg caching
      - name: Export GitHub Actions cache environment variables
        if: inputs.caching_enabled
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Export env variables for vcpkg caching
        if: inputs.caching_enabled
        run: echo "VCPKG_BINARY_SOURCES=clear;x-gha,readwrite" >> $GITHUB_ENV

      - name: Export env variable for arm64 build
        if: matrix.arch == 'arm64'
        run: echo "VCPKG_FORCE_SYSTEM_BINARIES=true" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go-worker/go.mod
          cache-dependency-path: go-worker/go.sum

      - name: Install zig
        uses: falcosecurity/libs/.github/actions/install-zig@master

      - name: Build plugin library
        run: make

      # Make sure we link the correct glibc version.
      - name: Test library glibc version
        run: |
          cd build
          objdump -T libcontainer.so | grep -Eo 'GLIBC_\S+' | sort -u -t "." -k1,1n -k2,2n -k3,3n
          linked_glibc=$(objdump -T libcontainer.so | grep -Eo 'GLIBC_\S+' | sort -u -t "." -k1,1n -k2,2n -k3,3n | tail -n1 | tr -d ')')
          if [ "$linked_glibc" != "GLIBC_2.17" ]; then
            echo "Expected glibc 2.17; found $linked_glibc"
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: libcontainer-${{ matrix.arch }}
          path: 'libcontainer.so'